name = "panel"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true

routes = [
  
  { pattern = "ouzora.dpdns.org", custom_domain = true },  
  { pattern = "collection.linefriends.com.ouzora.dpdns.org", custom_domain = true },  
  { pattern = "support.zoom.us.ouzora.dpdns.org", custom_domain = true },  
  { pattern = "ava.game.naver.com.ouzora.dpdns.org", custom_domain = true },

  ]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
